
name: "Build"
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build release
      run: nix develop --command make all
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: firmware.hex
        path: bin/main.hex

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build release
      run: nix develop --command clang-format --dry-run -Werror -style=file -i src/**.{h,c}
