on:
  push: {}
  pull_request:
    types: [opened, reopened, synchronize]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: smk
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build release
      run: nix develop --command make all
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/*.hex

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: smk
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Lint
      run: nix develop --command bash -c 'find src/ -iname "*.h" -o -iname "*.c" -print0 | xargs -0 -n1 -- clang-format --dry-run -Werror -style=file -i'

